# Ejercicio Clase 4

In [3]:
import numpy as np

n_dados = int(input("Inserte el numero de dados"))
n_lanzamientos = int(input("Inserte el numero de lanzamientos"))

for i in range(n_lanzamientos):
    suma_dados = 0
    print(f"Lanzamiento {i+1}")
    for j in range(n_dados):
        numero_al_azar = np.random.randint(1, 7)
        print(f"Dado {j+1} = {numero_al_azar}")
        suma_dados = numero_al_azar + suma_dados
    print(f"Suma total = {suma_dados}\n")

Lanzamiento 1
Dado 1 = 6
Dado 2 = 3
Dado 3 = 1
Suma total = 10

Lanzamiento 2
Dado 1 = 2
Dado 2 = 1
Dado 3 = 3
Suma total = 6

Lanzamiento 3
Dado 1 = 4
Dado 2 = 4
Dado 3 = 1
Suma total = 9

Lanzamiento 4
Dado 1 = 6
Dado 2 = 3
Dado 3 = 4
Suma total = 13

Lanzamiento 5
Dado 1 = 1
Dado 2 = 5
Dado 3 = 4
Suma total = 10

Lanzamiento 6
Dado 1 = 4
Dado 2 = 1
Dado 3 = 3
Suma total = 8



In [6]:
import numpy as np

n_dados = int(input("Inserte el número de dados: "))
n_lanzamientos = int(input("Inserte el número de lanzamientos: "))

lanzamientos = np.random.randint(1, 7, size=(n_lanzamientos, n_dados))

print(lanzamientos)

sumas = np.sum(lanzamientos, axis=1)
print(sumas)

for i, suma in enumerate(sumas):
    print(f"Lanzamiento {i+1}: {lanzamientos[i]} --> Suma total = {suma}")

[[5 5 4]
 [1 2 3]
 [1 2 3]
 [5 5 4]
 [5 3 2]]
[14  6  6 14 10]
Lanzamiento 1: [5 5 4] --> Suma total = 14
Lanzamiento 2: [1 2 3] --> Suma total = 6
Lanzamiento 3: [1 2 3] --> Suma total = 6
Lanzamiento 4: [5 5 4] --> Suma total = 14
Lanzamiento 5: [5 3 2] --> Suma total = 10
